Importação das bibliotecas necessárias

In [2]:
import numpy as np

In [9]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(a)

[1 2 3]


In [10]:
print(type(a), a.shape, a[0], a[1], a[2])
print(a)
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[1 2 3]
[5 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
print(type(b), b.shape, b[0,0], b[1,0])

<class 'numpy.ndarray'> (2, 3) 1 4


In [101]:
e = np.random.randint(10, size=(2, 5))
print(e)

[[9 3 6 6 8]
 [7 4 2 1 6]]


In [102]:
p = np.random.randint(10, size=(2, 5))
print(p)

[[7 9 9 1 1]
 [8 3 5 6 3]]


In [103]:
print(p.shape)

(2, 5)


In [104]:
r = np.append(e, p, axis=0)
print(r)

[[9 3 6 6 8]
 [7 4 2 1 6]
 [7 9 9 1 1]
 [8 3 5 6 3]]


In [105]:
print(r.shape)

(4, 5)


Função fast-non-dominated-sort responsável por classificar as soluções.

In [106]:
def teste(population):
    n_p = 0
    S_p = 0
    for p in population:
        print(p, p.shape)
        
        for q in p:
            print(q, q.shape)
        
        n_p = n_p + 1
        
    #for p in range(len(population)):
        #print(p, population(p))
        

SyntaxError: unexpected EOF while parsing (<ipython-input-107-9498fda08da7>, line 10)

In [108]:
fast_non_dominated_sort(r)

[9 3 6 6 8] (5,)
[7 4 2 1 6] (5,)
[7 9 9 1 1] (5,)
[8 3 5 6 3] (5,)


In [109]:
print(r[1,])

[7 4 2 1 6]


In [117]:
a = r[2,] <= r[1,]
b = np.array_equal(r[2,], r[1,])
print(a, b)

[ True False False  True  True] False


In [180]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 6, 2])

a = x <= y
b = np.array_equal(x, y)
print(a, b)

[ True  True  True False] False


In [415]:
def dominates(ind1, ind2):
    
    r1 = np.array_equal(ind1, ind2)
    if r1 == True:
        #print("1")
        return False
    
    v = ind1 <= ind2
    r2 = True
    for b in v:  
        #print("2")
        if b == False:
            return False
        #print("3")
        
        
    return True

In [421]:
def fast_non_dominated_sort(P):

    for p in P:
        #print(p, p.shape)        

        n_p = 0
        S_p = list()
        F = list()
        
        #print('eee= ')
        for q in P:
            #print('eee2= ', p, q)
            if dominates(p, q):
                S_p.append(q) 
                #print('a= ', S_p)
            elif dominates(q, p):
                n_p = n_p + 1
                #print('b= ', n_p)
              
        if n_p == 0:
            p_rank = 1
            F.append(p) 
            #print('c= ', F)        
        
    i = 0
    for x in F:
        Q = list()
        
        for p in F[i]:
            for q in S_p:
                n_q = n_p - 1
                #print('d= ', n_q)
                
                if n_q == 0:
                    q_rank = i + 1
                    Q.append(q)
                    #print('e= ', Q)
                    
        i = i + 1
        if (len(F)-1) == i:
            F[i] = Q        
            

In [422]:
r = np.random.randint(10, size=(2, 2))
print(r)

[[4 8]
 [0 2]]


In [423]:
fast_non_dominated_sort(r)